language: node_js

matrix:
  include:
    - node_js: "8.10"
    - node_js: "10.13.0"

git:
  quiet: true
  depth: 5

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.15.2
  - export PATH="$HOME/.yarn/bin:$PATH"

stages:
  - test
  - build
  - deploy

jobs:
  include:
    - stage: test
      script:
        - yarn test
    - stage: build
      script:
        - echo "building"
    - stage: deploy
      script:
        - echo "deploying"

after_success:
  - echo $TRAVIS_TEST_RESULT
