language: node_js

node_js:
  - "8.10"
  - "10.13.0"
os:
  - linux
  - osx

git:
  quiet: true
  depth: 5

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.15.2
  - export PATH="$HOME/.yarn/bin:$PATH"

stages:
  - test
  - deploy

jobs:
  include:
    - stage: test
      script:
        - yarn test     
    - stage: deploy
      if: branch = master
      node_js: "8.10"
      before_script:
        - yarn run compile
      script:
        - echo "deploying"

after_success:
  - echo $TRAVIS_TEST_RESULT
